name: test-on-main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 pyInstall dependencies
        run: |
          pip install -r laboratories/cicd-documentation/requirements.txt || true

      - name: 🧪 Run unit tests
        run: |
          cd laboratories/cicd-documentation
          pytest test_tree.py